---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "update"
      command: sudo apt-get update
      register: details
      
    - name: "docker setup "
      command: sudo snap install docker
      register: details
      
    - name: "docker deploy 1"
      command: echo 123456 | sudo -S chmod 666 /var/run/docker.sock
      register: details
      
    - name: "docker deploy 2"
      command: docker run -i -t nginx:stable-perl /bin/bash
      register: details
      
    - name: "docker ps"
      command: docker ps
      register: details
