---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "user verification"
      command: whoami
      register: details
    - name: "update"
      command: sudo apt-get update
      register: details
    - name: "docker setup"
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      command: sudo apt-get update
      command: apt-cache policy docker-ce
      command: sudo apt-get install -y docker-ce
      register: details
    - name: "docker check"
      command: sudo systemctl status docker
      register: details
    - name: "container deploy"
      command: docker search redis
      command: docker pull redis
      command: docker run -d redis
      register: details
    - name: "docker ps"
      command: docker ps
      register: details
