---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "user verification"
      command: whoami
      register: details
    - name: "update"
      command: sudo apt-get update
      register: details
    - name: "python setup"
      
      command: sudo apt install -y python3-pip

      register: details
    - name: "docker setup"
      command: pip3 install docker
      register: details
    - name: deploy nginx docker container
    docker_container:
      image: nginx:stable
      name: nginx
      state: started
      auto_remove: true
      ports:
        - "8090:80"
    - name: "docker ps"
      command: docker ps
      register: details
