---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "user verification"
      command: whoami
      register: details
    - name: "update"
      command: sudo apt-get update
      register: details
    - name: "python setup"
      
      command: sudo apt install -y python3-pip

      register: details
    - name: "docker setup"
      command: pip3 install docker
      
      register: details
    - name: "docker setup 2"
      
      command: sudo snap install docker
      register: details
    - name: "docker deploy 1"
      
      command: docker run -i -t ubuntu:latest /bin/bash
      register: details
    - name: "docker deploy 2"
      command: sudo chmod 666 /var/run/docker.sock
      
      register: details
    - name: "docker ps"
      command: docker ps
      register: details
